// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yshnqlluaftmmiafyhqb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlzaG5xbGx1YWZ0bW1pYWZ5aHFiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYyMzE1ODEsImV4cCI6MjA3MTgwNzU4MX0.y0lqYMl30TD1AR3EY52dEYAjQL8rn0caGrTZDbP0-IE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});